package autocode

type ServiceGroup struct {
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.
	AutoCodeExampleService
	MinappSetService
	MinappUserService
	AgreementService
	HelpMeService
	BannerService
	AreaService
	CouponService
	ReleaseRecordService
	ComplaintLabelService
	ComplaintService
	HelpRepairService
	HelpWorkService
	HelpFetchService
	HelpBuyService
	HelpIncidentallyService
	HelpCarpoolService
	HelpGrouponService
	HelpSecondService
	CategoryService
	CheckDriverService
	CheckMerchantService
	CreditRatingService
	PayCouponService
	WithdrawService
	CommissionService
	SystemMessageService
	CheckIdentityService
	MoneyRecordService
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}
