package autocode

import "github.com/flipped-aurora/gin-vue-admin/server/service"

type ApiGroup struct {
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.
	AutoCodeExampleApi
	MinappSetApi
	MinappUserApi
	AgreementApi
	HelpMeApi
	BannerApi
	AreaApi
	CouponApi
	ReleaseRecordApi
	ComplaintLabelApi
	ComplaintApi
	HelpRepairApi
	HelpWorkApi
	HelpFetchApi
	HelpBuyApi
	HelpIncidentallyApi
	HelpCarpoolApi
	HelpGrouponApi
	HelpSecondApi
	CategoryApi
	CheckDriverApi
	CheckMerchantApi
	CreditRatingApi
	PayCouponApi
	WithdrawApi
	CommissionApi
	SystemMessageApi
	CheckIdentityApi
	MoneyRecordApi
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}

var (
	redisService = service.ServiceGroupApp.MinAppServiceGroup.RedisService
)
