package autocode

type RouterGroup struct {
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.
	AutoCodeExampleRouter
	MinappSetRouter
	MinappUserRouter
	AgreementRouter
	HelpMeRouter
	BannerRouter
	AreaRouter
	CouponRouter
	ReleaseRecordRouter
	ComplaintLabelRouter
	ComplaintRouter
	HelpRepairRouter
	HelpWorkRouter
	HelpFetchRouter
	HelpBuyRouter
	HelpIncidentallyRouter
	HelpCarpoolRouter
	HelpGrouponRouter
	HelpSecondRouter
	CategoryRouter
	CheckDriverRouter
	CheckMerchantRouter
	CreditRatingRouter
	PayCouponRouter
	WithdrawRouter
	CommissionRouter
	SystemMessageRouter
	CheckIdentityRouter
	MoneyRecordRouter
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}
